{% set version = "0.6.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pander
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pander_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pander/pander_{{ version }}.tar.gz
  sha256: 2add076bd2ca6749715a044e26baf1e0aee5d50211903ee6bfceecc30b9e9f90

build:
  merge_build_host: true  # [win]
  skip: true              # [ppc64le]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-digest
    - pandoc
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-digest
    - pandoc

test:
  commands:
    - $R -e "library('pander')"           # [not win]
    - "\"%R%\" -e \"library('pander')\""  # [win]

about:
  home: http://rapporter.github.io/pander
  license: AGPL-3.0-only
  summary: "Contains some functions catching all messages, 'stdout' and other useful information while evaluating R code and other helpers to return user specified text elements (like: header, paragraph, table, image, lists etc.) in 'pandoc' markdown or several type of R objects similarly automatically transformed to markdown\
    \ format. Also capable of exporting/converting (the resulting) complex 'pandoc' documents to e.g. HTML, 'PDF', 'docx' or 'odt'. This latter reporting feature is supported in brew syntax or with a custom reference class with a smarty caching 'backend'."
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
