# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EwgLOhl99BwRfBKh7HhtWwyjKWFCCjsQkHVnHujHBBTWtJe1tkO0108mbsYM0yGRNdULLF8oK7CNvrzQUPFAwhwwZ0CXCsrx5IjJzg+nzK6af26UYEnD6YbZYDpmxhHkDL9+kgf35lqXWmGme10Z+MjaPuFHj6L/UJggB0dgCpdtZ08CsgUhVlOJzpJI5qknnstbBgBp6R4z6PNCtn6azhR4h99nqofruv6l6YMdUkSH7o9qKGMjFODwNCModNkQiEw+OIgEiLdWVxrnjGAuUqMTbNerFciQQnru6FvzdQs3K9cmbJStc8c/5lzr6PXVJHf2M1uo+eMhQZAA7Rc1x3AcwpL2TaWHfOldGOfYnLwMJRoKxECWw7r6CKi492rBinl9/ucBg8i97ZTBN6BXtUpiF2fsb0PCsT83v/rheH/viZlvKwERFtgQLrn0nJ6NY0eaUNr1UF4a0O1RdVzNEuC98cVUJ1KnIyknXYdrL3ALduY3M6jONWvqkXvrBEDhFi+NqcXcXReiJjZH3GIHbAr21t4Q6iYR84081UPROVH26sSaBja+7M3fTVgWKfXOVs170zAcSvzmvCjEk25nKmnXAPQrk2r6S81+JNQsMbiyfllxpUwlThbcVwdY9yn6DcbhLsXh1Epon5ULqS075GQ0ns+7bg2ZWAwfVcYQzFI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
