appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EwgLOhl99BwRfBKh7HhtWwyjKWFCCjsQkHVnHujHBBTWtJe1tkO0108mbsYM0yGRNdULLF8oK7CNvrzQUPFAwhwwZ0CXCsrx5IjJzg+nzK6af26UYEnD6YbZYDpmxhHkDL9+kgf35lqXWmGme10Z+MjaPuFHj6L/UJggB0dgCpdtZ08CsgUhVlOJzpJI5qknnstbBgBp6R4z6PNCtn6azhR4h99nqofruv6l6YMdUkSH7o9qKGMjFODwNCModNkQiEw+OIgEiLdWVxrnjGAuUqMTbNerFciQQnru6FvzdQs3K9cmbJStc8c/5lzr6PXVJHf2M1uo+eMhQZAA7Rc1x3AcwpL2TaWHfOldGOfYnLwMJRoKxECWw7r6CKi492rBinl9/ucBg8i97ZTBN6BXtUpiF2fsb0PCsT83v/rheH/viZlvKwERFtgQLrn0nJ6NY0eaUNr1UF4a0O1RdVzNEuC98cVUJ1KnIyknXYdrL3ALduY3M6jONWvqkXvrBEDhFi+NqcXcXReiJjZH3GIHbAr21t4Q6iYR84081UPROVH26sSaBja+7M3fTVgWKfXOVs170zAcSvzmvCjEk25nKmnXAPQrk2r6S81+JNQsMbiyfllxpUwlThbcVwdY9yn6DcbhLsXh1Epon5ULqS075GQ0ns+7bg2ZWAwfVcYQzFI=
conda_forge_output_validation: true
